#include "objects.h"
#include "rv.h"

void __attribute__((__section__(".obj5a5-0"))) obj5a5_p0(void) {
	//32 instructions
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
}
void __attribute__((__section__(".obj5a5-1"))) obj5a5_p1(void) {
	//32 instructions
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
}
void __attribute__((__section__(".obj5a5-2"))) obj5a5_p2(void) {
	//32 instructions
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
}
void __attribute__((__section__(".obj5a5-3"))) obj5a5_p3(void) {
	//32 instructions
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
}
void __attribute__((__section__(".obj5a5-persist"))) obj5a5_persist(void) {
	//96 instructions
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
	asm("add a0,zero,zero");
}
void obj5a5(void) {
	obj5a5_p0();
	obj5a5_p1();
	obj5a5_p2();
	obj5a5_p3();
	obj5a5_persist();
}

void object(2)
object02(void)
{
	obj5a5();
}
